version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    container_name: acid_lab_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: acid_lab
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data